Prepare for rpc connection
milvus-io/milvus-sdk-cpp pull request #24
Opened 2021-11-30 11:11 UTC by yhmo

Signed-off-by: yhmo <yihua.mo@zilliz.com>

2021-11-30 20:24 UTC, ArkaprabhaChakraborty commented
I think this is some file pathway error in the CMakeLists.txt which causes the build to fail 
```
Make Error at src/CMakeLists.txt:36 (add_library):
  Cannot find source file:

    /home/runner/work/milvus-sdk-cpp/milvus-sdk-cpp/src/proto-gen/milvus.grpc.pb.cc
```

2021-12-01 02:31 UTC, matrixji requested changes
Generate proto to pc.cc need some fix, other changes look good to me

2021-12-01 02:31 UTC, matrixji commented on src/proto-gen/proto-gen.cmake
> +        OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/proto-gen/${name}.pb.cc
I guess neet change ${name}.pb.cc => ${name}.grpc.pb.cc

2021-12-01 02:59 UTC, yhmo commented
Ok, I have fixed the cmake error. Still has lint error.

2021-12-01 04:51 UTC, matrixji commented
/lgtm

2021-12-01 04:53 UTC, merged