Add CreateIndex() method
milvus-io/milvus-sdk-cpp pull request #73
Opened 2021-12-12 15:56 UTC by ArkaprabhaChakraborty

Fixes #62 
Signed-off-by: ArkaprabhaChakraborty <chakrabortyarkaprabha998@gmail.com>

2021-12-13 03:10 UTC, yhmo commented
Still has lint error. @ArkaprabhaChakraborty

2021-12-13 10:46 UTC, ArkaprabhaChakraborty commented
Yes Ill fix it by tomorrow.

2021-12-15 21:28 UTC, ArkaprabhaChakraborty commented
@matrixji @yhmo how to fix the codecov error?

2021-12-15 23:42 UTC, matrixji commented
I guess codecov is decreased due to your PR not rebasing from the latest in master. We're not setting codecov as mandatory right now.
Look's good to me, except need to squash your 3 commits to one in this PR.

2021-12-16 05:50 UTC, ArkaprabhaChakraborty commented
Then it should have had conflicts, shouldn't it? But it doesnt say any merge conflicts or something like that.

2021-12-16 08:33 UTC, ArkaprabhaChakraborty commented
@matrixji @yhmo

2021-12-16 08:56 UTC, matrixji commented
Hi, @ArkaprabhaChakraborty. I see the reason why coverage failed, seems you have disabled your testing code.

2021-12-16 09:00 UTC, matrixji requested changes

2021-12-16 09:00 UTC, matrixji commented on test/it/TestCreateIndex.cpp
> +TEST_F(MilvusMockedTest, DISABLED_TestCreateIndex) {
I guess this is the reason why coverage failed, the test did not run as DESIABLE_ prefix.

2021-12-16 09:00 UTC, matrixji commented on test/it/TestCreateIndex.cpp
> +
I think here we need to add some EXPECT_CALLs here for matching the mocker calls

2021-12-16 09:00 UTC, ArkaprabhaChakraborty commented
> Hi, @ArkaprabhaChakraborty. I see the reason why coverage failed, seems you have disabled your testing code.

Yes because the current test also depends on another method which is not yet completed

2021-12-16 09:01 UTC, ArkaprabhaChakraborty commented
I want to make changes to this test later as it requires DescribeIndex() method too

2021-12-16 09:06 UTC, ArkaprabhaChakraborty commented on test/it/TestCreateIndex.cpp
> +
I don't know how to add this.

2021-12-16 09:08 UTC, ArkaprabhaChakraborty commented on test/it/TestCreateIndex.cpp
> +TEST_F(MilvusMockedTest, DISABLED_TestCreateIndex) {
Yes I have DISABLED the test as it requires DescribeIndex() too. But the error was:
```
Uninteresting mock function call - returning default value.
Function call: CreateIndex(0x7f35dc00c200, 0x7f35dc00ae50, 0x7f35f144e790)
          Returns: 72-byte object <00-00 00-00 00-00 00-00 30-CA 00-DC 35-7F 00-00 00-00 00-00 00-00 00-00 00-6B 12-F5 35-7F 00-00 50-1B 00-DC 35-7F 00-00 50-CA 00-DC 35-7F 00-00 00-00 00-00 00-00 00-00 00-56 58-86 3A-69 ED-60 C0-E3 44-F1 35-7F 00-00>
```

2021-12-16 10:54 UTC, matrixji commented
> I want to make changes to this test later as it requires DescribeIndex() method too

For now, as we are in the early stage, IMO it's acceptable to add test code later.
/lgtm

2021-12-16 10:55 UTC, merged